### ISSUE TITLE
RuntimeError: torch.linalg.eigh: the algorithm failed to converge

### ISSUE THREAD

**Issue by RahulBhalley** [JCBrouwer/OptimalTextures#3]
Hi @JCBrouwer, thank you so much for implementing this! Unfortunately, I'm unable to run this. 

1. I am using M1 Mac so `torch==1.8` is not available so I installed `torch==1.9` and `torchvision==0.10`.
2. Then I ran into issue saying the following
```
UserWarning: torch.symeig is deprecated in favor of torch.linalg.eigh and will be removed in a future PyTorch release.
The default behavior has changed from using the upper triangular portion of the matrix by default to using the lower triangular portion.
L, _ = torch.symeig(A, upper=upper)
should be replaced with
L = torch.linalg.eigvalsh(A, UPLO='U' if upper else 'L')
and
L, V = torch.symeig(A, eigenvectors=True)
should be replaced with
L, V = torch.linalg.eigh(A, UPLO='U' if upper else 'L') (Triggered internally at  ../aten/src/ATen/native/BatchLinearAlgebra.cpp:2500.)
  eva_t, eve_t = torch.symeig(cov_t, eigenvectors=True, upper=True)
Traceback (most recent call last):
```
3. Then I changed the code accordingly.
4. Now, I get the error as following for style transfer: `python optex.py --style style/lava-small.jpg --content content/rocket.jpg --content_strength 0.2`
```
Current resolution: 256, current layer relu1_1:  23%|████████████████████▉                                                                      | 115/500 [00:03<00:11, 32.30it/s]Traceback (most recent call last):
  File "/Users/rahulbhalley/Desktop/OptimalTextures/optex.py", line 304, in <module>
    output = optimal_texture(**vars(args))
  File "/Users/rahulbhalley/Desktop/OptimalTextures/optex.py", line 89, in optimal_texture
    output_layer = optimal_transport(output_layer, style_layers[l], hist_mode)
  File "/Users/rahulbhalley/Desktop/OptimalTextures/optex.py", line 127, in optimal_transport
    matched_output = hist_match(rotated_output, rotated_style, mode=hist_mode)
  File "/Users/rahulbhalley/Desktop/OptimalTextures/histmatch.py", line 34, in hist_match
    eva_t, eve_t = torch.linalg.eigh(cov_t, UPLO='U')
RuntimeError: torch.linalg.eigh: the algorithm failed to converge; 24 off-diagonal elements of an intermediate tridiagonal form did not converge to zero.
```

How to fix this issue? 

Best,
Rahul Bhalley

**Comment by RahulBhalley** [comment]
Okay, so I was able to run this by upgrading torch to v1.13.1 after using `torch.linalg.eigh ` instead of `torch.symeig`. 

But to surprise M1 Mac CPU-based optimization is faster than P100 GPU:
- 00:44 vs 01:01 for `python optex.py --style style/graffiti.jpg --size 512`.
- 00:28 vs 00:52 for `python optex.py --style style/green-paint-large.jpg --content content/city.jpg --content_strength 0.1`. 

Anyways, thanks for your implementation. Reading the paper title (**fast**) I thought it was a non-optimization (just inference) method. But it's good to try it out.
